name: ezDB Tests
on: [push, pull_request, workflow_dispatch]

env:
  ezDB_driver: mysql
  ezDB_host: localhost
  ezDB_port: 3306
  ezDB_db: ezdb_tests
  ezDB_user: root
  ezDB_pass: root

jobs:        
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        experimental: [false]
      
    steps:
      - name: Checkout ezDB
        uses: actions/checkout@v2
        
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mysql
          
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ezdb_tests;' -uroot -proot
          mysql -h localhost -u root -proot ezdb_tests < tests/Data/schema/mysql.sql

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
        
      - name: Run Tests
        run: php vendor/bin/phpunit --configuration tests/phpunit.xml